export const DUMMY_BLOGS = [
  {
    id: "dummy-1",
    slug: "future-of-ai-in-2025",
    title: "The Future of Artificial Intelligence in 2025",
    author: "Persevex AI Team",
    description: "Explore the most anticipated AI breakthroughs expected to revolutionize industries this year.",
    content: "Artificial Intelligence is no longer just a buzzword; it's a fundamental shift in how we approach problem-solving.\n\nFrom advanced generative models to hyper-personalized learning platforms, AI will become even more ingrained in our daily workflows. Students and professionals alike must adapt to *using* AI effectively.\n\n## Key Trends:\n1. **Agential AI**: Systems that learn and execute complete tasks rather than just generating text.\n2. **AI in Education**: Tailored curriculums that adapt to individual learning speeds.\n3. **Ethics and Safety**: More robust frameworks to ensure responsible AI deployments.\n\nThe real question is: are you ready to harness these tools?",
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "dummy-2",
    slug: "mastering-react-19",
    title: "Mastering React 19: What You Need to Know",
    author: "Frontend Guild",
    description: "React 19 brings exciting new features like the React Compiler and Actions. Here's a quick overview.",
    content: "React 19 has officially launched, and it promises to drastically reduce the boilerplate we write.\n\n### The React Compiler\nForget about `useMemo` and `useCallback`. The new compiler optimizes your UI automatically.\n\n### Actions\nHandling data mutations used to be tedious. With Actions, managing pending states and form submissions is built deeply into React.\n\nStart upgrading your codebases today and take advantage of these massive performance boosts!",
    createdAt: new Date("2025-02-15T09:30:00Z"),
    updatedAt: new Date("2025-02-15T09:30:00Z"),
  },
  {
    id: "dummy-3",
    slug: "why-cybersecurity-is-crucial",
    title: "Why Cybersecurity is the Most Crucial Skill Right Now",
    author: "Security Experts",
    description: "As businesses move completely to the cloud, the demand for skilled cybersecurity professionals is at an all-time high.",
    content: "Every week, a new data breach makes the headlines. It has never been more obvious: we need more security experts.\n\nIf you're considering a career pivot, **Cybersecurity** offers unprecedented job security and lucrative compensation.\n\nLearning the basics of network security, ethical hacking, and risk management can give you a massive edge in the current job market.",
    createdAt: new Date("2025-02-20T14:45:00Z"),
    updatedAt: new Date("2025-02-20T14:45:00Z"),
  },
  {
    id: "dummy-4",
    slug: "getting-started-with-data-science",
    title: "Getting Started with Data Science",
    author: "Data Wizards",
    description: "A simple guide to taking your first steps in the intimidating world of Data Science and Analytics.",
    content: "Data Science might sound complex, but at its core, it's just about finding patterns in information.\n\n**Where to grab those skills?**\n- Learn Python or R.\n- Understand statistical basics.\n- Practice with real-world datasets from Kaggle.\n\nDon't let the complex math scare you away. Start small, build intuitions, and your skills will naturally compound!",
    createdAt: new Date("2025-02-25T11:15:00Z"),
    updatedAt: new Date("2025-02-25T11:15:00Z"),
  },
  {
    id: "dummy-5",
    slug: "cloud-computing-career-growth",
    title: "How Cloud Computing Can Accelerate Your Career Growth",
    author: "Cloud Architects",
    description: "Discover how mastering cloud platforms like AWS, Azure, and Google Cloud can transform your professional trajectory.",
    content: "Cloud computing has fundamentally changed how businesses operate, and professionals with cloud expertise are in tremendous demand.\n\n## Why Cloud Skills Matter:\n- **Remote Work Enablement**: Cloud infrastructure powers the modern remote workforce\n- **Scalability**: Companies need experts who understand elastic computing\n- **Cost Optimization**: Organizations seek professionals who can reduce IT costs\n\n### Getting Started:\n1. **Choose Your Platform**: Start with AWS, Azure, or Google Cloud\n2. **Hands-On Practice**: Build actual projects, don't just watch tutorials\n3. **Certifications**: Validate your skills with vendor-specific certifications\n\nAt Persevex, we've helped over 10,000+ students transition into cloud roles. The demand continues to grow exponentially!",
    createdAt: new Date("2025-02-26T16:20:00Z"),
    updatedAt: new Date("2025-02-26T16:20:00Z"),
  },
  {
    id: "dummy-6",
    slug: "machine-learning-projects-guide",
    title: "5 Machine Learning Projects Every Beginner Should Build",
    author: "ML Engineering Team",
    description: "Practical project ideas that will help you build a strong foundation in machine learning and impress potential employers.",
    content: "Building real projects is the fastest way to learn machine learning. Here are 5 projects that will teach you essential concepts while creating an impressive portfolio.\n\n### 1. Predictive Analytics Dashboard\nBuild a system that predicts sales, stock prices, or website traffic using historical data.\n\n### 2. Recommendation Engine\nCreate a movie or product recommendation system using collaborative filtering.\n\n### 3. Image Classification Model\nTrain a CNN to classify images - start with simple datasets like CIFAR-10.\n\n### 4. Natural Language Processing Sentiment Analyzer\nBuild a tool that analyzes customer reviews or social media sentiment.\n\n### 5. Time Series Forecasting\nPredict future values based on historical patterns - great for business applications.\n\n## Pro Tips:\n- **Use Real Data**: Kaggle competitions provide excellent datasets\n- **Document Everything**: Write clear README files and code comments\n- **Deploy Your Models**: Use platforms like Streamlit or Heroku to make your projects accessible\n\nRemember, employers care more about what you can build than what you know in theory!",
    createdAt: new Date("2025-02-27T13:45:00Z"),
    updatedAt: new Date("2025-02-27T13:45:00Z"),
  },
];
